export const SHARED_BROADCAST_CHANNEL_NAME = "SHAREDWORKER_BROADCAST";
export const FORCE_LEADER_ELECTION = "FORCE_LEADER_ELECTION";
export const DB_NOT_INIT_ERR = "DB_NOT_INIT";
export const WORKER_LOCK_KEY = "WORKER_LOCK";
export const DB_LOCK_ACQUIRED = "DB_LOCK_ACQUIRED";
export const NOROW = Symbol("NOROW");
